//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environment_Green.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnvoGreen_ModelContainer : DbContext
    {
        public EnvoGreen_ModelContainer()
            : base("name=EnvoGreen_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Energy> Energies { get; set; }
        public virtual DbSet<Water> Waters { get; set; }
        public virtual DbSet<Household> Households { get; set; }
        public virtual DbSet<Electricity> Electricities { get; set; }
        public virtual DbSet<DwellingType> DwellingTypes { get; set; }
        public virtual DbSet<Employed> Employeds { get; set; }
        public virtual DbSet<Winter> Winters { get; set; }
        public virtual DbSet<WinterDwelling> WinterDwellings { get; set; }
        public virtual DbSet<Timeline> Timelines { get; set; }
        public virtual DbSet<Summer> Summers { get; set; }
        public virtual DbSet<SummerDwelling> SummerDwellings { get; set; }
    }
}
