//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environment_Green.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizResult
    {
        public int Id { get; set; }
        public string State { get; set; }
        public int Occupants { get; set; }
        public double Income { get; set; }
        public double EnergyBills { get; set; }
        public double WaterBills { get; set; }
        public string HeaterType { get; set; }
        public int HeaterDuration { get; set; }
        public string WMType { get; set; }
        public int WashingFrequency { get; set; }
        public int Room { get; set; }
        public string BulbType { get; set; }
        public int BulbDuration { get; set; }
    }
}
