//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environment_Green.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Water
    {
        public int WaterId { get; set; }
        public int Year { get; set; }
        public string State { get; set; }
        public int AvgHouseholdConsumption { get; set; }
        public int TotalConvention { get; set; }
        public int TotalExpenditure { get; set; }
    
        public virtual Energy Energy { get; set; }
    }
}
