//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environment_Green.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Winter()
        {
            this.WinterDwellings = new HashSet<WinterDwelling>();
        }
    
        public int WinterId { get; set; }
        public string ApplianceType { get; set; }
        public int WeeklyConsumption { get; set; }
        public int WeeklyFee { get; set; }
        public int AvgHours { get; set; }
        public int AvgTemperature { get; set; }
        public string ElectricitySeasonType { get; set; }
    
        public virtual Electricity Electricity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WinterDwelling> WinterDwellings { get; set; }
    }
}
