//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Environment_Green.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinterDwelling
    {
        public int WinterDwellingId { get; set; }
        public string Housetype { get; set; }
        public string Yearline { get; set; }
        public int PercentageCost { get; set; }
        public int WinterWinterId { get; set; }
    
        public virtual Winter Winter { get; set; }
        public virtual DwellingType DwellingType { get; set; }
        public virtual Timeline Timeline { get; set; }
    }
}
